instead of adding another escape, protect the backrefs as they're passed to sed.
/bin/dash on debian/ubuntu was getting 0x01 instead of the backref passed to sed:
  > fcgid_config.h:4:9: error: macro names must be identifiers

Tested on /bin/dash, /bin/bash on Linux and /bin/sh, /usr/xpg4/bin/sh on Solaris.

Submitted by: Eric Covener, Igor Galić
Reviewed by: Eric Covener



git-svn-id: https://svn.apache.org/repos/asf/httpd/mod_fcgid/trunk@950693 13f79535-47bb-0310-9956-ffa450edef68